<?php //create submission custom post type

if ( ! function_exists('go_submission') ) {

// Register Custom Post Type
function go_submission() {

	$labels = array(
		'name'                  => _x( 'Submissions', 'Post Type General Name', 'goodorbit_challenge' ),
		'singular_name'         => _x( 'Submission', 'Post Type Singular Name', 'goodorbit_challenge' ),
		'menu_name'             => __( 'Submissions', 'goodorbit_challenge' ),
		'name_admin_bar'        => __( 'Submission', 'goodorbit_challenge' ),
		'archives'              => __( 'Submission Archives', 'goodorbit_challenge' ),
		'attributes'            => __( 'Submission Attributes', 'goodorbit_challenge' ),
		'parent_item_colon'     => __( 'Parent Submission:', 'goodorbit_challenge' ),
		'all_items'             => __( 'All Submissions', 'goodorbit_challenge' ),
		'add_new_item'          => __( 'Add New Submission', 'goodorbit_challenge' ),
		'add_new'               => __( 'Add New', 'goodorbit_challenge' ),
		'new_item'              => __( 'New Submission', 'goodorbit_challenge' ),
		'edit_item'             => __( 'Edit Submission', 'goodorbit_challenge' ),
		'update_item'           => __( 'Update Submission', 'goodorbit_challenge' ),
		'view_item'             => __( 'View Submission', 'goodorbit_challenge' ),
		'view_items'            => __( 'View Submissions', 'goodorbit_challenge' ),
		'search_items'          => __( 'Search Submission', 'goodorbit_challenge' ),
		'not_found'             => __( 'Not found', 'goodorbit_challenge' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'goodorbit_challenge' ),
		'featured_image'        => __( 'Featured Image', 'goodorbit_challenge' ),
		'set_featured_image'    => __( 'Set featured image', 'goodorbit_challenge' ),
		'remove_featured_image' => __( 'Remove featured image', 'goodorbit_challenge' ),
		'use_featured_image'    => __( 'Use as featured image', 'goodorbit_challenge' ),
		'insert_into_item'      => __( 'Insert into submission', 'goodorbit_challenge' ),
		'uploaded_to_this_item' => __( 'Uploaded to this submission', 'goodorbit_challenge' ),
		'items_list'            => __( 'Submissions list', 'goodorbit_challenge' ),
		'items_list_navigation' => __( 'Submissions list navigation', 'goodorbit_challenge' ),
		'filter_items_list'     => __( 'Filter submissions list', 'goodorbit_challenge' ),
	);
	$args = array(
		'label'                 => __( 'Submission', 'goodorbit_challenge' ),
		'description'           => __( 'Airport CSV Submissions', 'goodorbit_challenge' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'custom-fields' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-media-spreadsheet',
		'show_in_admin_bar'     => false,
		'show_in_nav_menus'     => false,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true,
	);
	register_post_type( 'submission', $args );

}
add_action( 'init', 'go_submission', 0 );

}

//Add ACF Fields

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62bb7e34cd251',
		'title' => 'Airport Locations',
		'fields' => array(
			array(
				'key' => 'field_62bb7e3fb2736',
				'label' => 'Submitted CSV',
				'name' => 'airport_csv',
				'type' => 'file',
				'instructions' => 'CSV file uploaded to create post.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'csv',
			),
			array(
				'key' => 'field_62bb7e6bb2737',
				'label' => 'Airport Locations',
				'name' => 'airport_locations',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_62bb7ea0b2739',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_62bb7e7eb2738',
						'label' => 'ID',
						'name' => 'id',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7ea0b2739',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7ebdb273a',
						'label' => 'City',
						'name' => 'city',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7ec6b273b',
						'label' => 'Country',
						'name' => 'country',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7ecdb273c',
						'label' => 'IATA/FAA',
						'name' => 'iata-faa',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7edfb273d',
						'label' => 'ICAO',
						'name' => 'icao',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7ee7b273e',
						'label' => 'Latitude',
						'name' => 'latitude',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7eefb273f',
						'label' => 'Longitude',
						'name' => 'longitude',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7efbb2740',
						'label' => 'Altitude',
						'name' => 'altitude',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62bb7f03b2741',
						'label' => 'Timezone',
						'name' => 'timezone',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'submission',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 1,
	));

endif;		